AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Stack containing all implementations for the amazon website along with the required layers.

Globals:
  Function:
    Timeout: 30

Resources:
  RequestHandlerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: request-handler-layer
      Description: "Python based request handler for serverless scrapers."
      ContentUri: request-handler/
      CompatibleRuntimes:
        - python3.13
    Metadata:
      BuildMethod: python3.13

  AmazonPdpFunction:
    Type: AWS::Serverless::Function
    Description: "Python based function to scrape and collect pdp data from amazon; all-domains"
    FunctionName: fabric-amazon-pdp
    Properties:
      CodeUri: amazon-pdp/
      Handler: main.entrypoint
      Runtime: python3.13
      Architectures:
        - x86_64
      Layers:
        - Ref: RequestHandlerLayer
      Environment:
        Variables:
          # Need to add these to ensure that --env-vars loads the required envs
          BD_PROXY_USERNAME: ""
          BD_PROXY_PASSWORD: ""
          BD_PROXY_HOSTNAME: ""
          BD_PROXY_PORT: ""
      # Role: "TODO"
